apiVersion: v1
kind: Pod
metadata:
  name: "initpod"
  namespace: default
  labels:
    app: "initpod"
spec:
  containers:
  - name: initpod
    image: "busybox:1.28"
    command: ["sh","-c","date && sleep 3600"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
    ports:
    - containerPort:  80
      name:  http
  initContainers:
  - name: init
    image: "busybox:1.28"
    command: ["sh","-c","date && sleep 10"]
  restartPolicy: Always